### ISSUE TITLE
catopy needs conda-forge

### ISSUE THREAD

**Issue by FeGeyer** [radionets-project/radionets#11]
Referenced in [here](https://stackoverflow.com/questions/53697814/using-pip-install-to-install-cartopy-but-missing-proj-version-at-least-4-9-0) and [here](https://github.com/googlecolab/colabtools/issues/85). At this time catopy is installed with `conda install --channel conda-forge cartopy`, but this comes with several, unwanted packages that are not necessary.

**Comment by Kevin2** [comment]
will be fixed in the next major refactoring
